# Generated by Django 2.2.7 on 2020-04-21 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('folio', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField()),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_banco', models.DateField(blank=True, null=True)),
                ('referencia_banco', models.CharField(blank=True, max_length=20, null=True)),
                ('interes_ord', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('interes_mor', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('abono_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estatus_actual', models.CharField(choices=[('VI', 'Vigente'), ('VE', 'Vencido')], max_length=2)),
                ('deuda_prev_total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('deuda_prev_int_ord', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('deuda_prev_int_mor', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
        ),
    ]
