# Generated by Django 2.2.7 on 2020-08-18 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_banco', models.DateField(blank=True, null=True)),
                ('referencia_banco', models.CharField(blank=True, max_length=20, null=True)),
                ('interes_ord', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('interes_mor', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('abono_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estatus_previo', models.CharField(choices=[('VI', 'Vigente'), ('VE', 'Vencido')], max_length=2)),
                ('deuda_prev_total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('deuda_prev_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('deuda_prev_int_ord', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('deuda_prev_int_mor', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pago_autor', to=settings.AUTH_USER_MODEL)),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='contratos.ContratoCredito')),
            ],
        ),
    ]
