# Generated by Django 2.2.7 on 2020-04-21 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contratos', '0002_contratocredito_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pago_autor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pago',
            name='credito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='contratos.ContratoCredito'),
        ),
    ]
