# Generated by Django 2.2.7 on 2020-04-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_pago_abono_capital'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='estatus_actual',
            field=models.CharField(choices=[('VI', 'Vigente'), ('VE', 'Vencido')], default='VI', max_length=2),
            preserve_default=False,
        ),
    ]
