# Generated by Django 2.2.7 on 2020-06-27 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_auto_20200609_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='referencia_banco_id',
        ),
    ]
