# Generated by Django 2.2.7 on 2020-04-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_pago_estatus_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='deuda_prev_int_mor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='deuda_prev_int_ord',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='deuda_prev_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
