# Generated by Django 2.2.7 on 2020-04-21 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoBanco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_concepto', models.CharField(max_length=40)),
                ('ingreso', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SubCuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cuenta', models.CharField(max_length=40)),
                ('proceso', models.CharField(blank=True, choices=[('CF', 'Café'), ('MI', 'Miel'), ('JA', 'Jabon'), ('SL', 'Sueldos')], max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoBanco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_banco', models.CharField(max_length=20, unique=True)),
                ('fecha', models.DateField()),
                ('referencia', models.CharField(max_length=60)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimiento_banco', to='bancos.ConceptoBanco')),
                ('sub_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimiento_banco', to='bancos.SubCuenta')),
            ],
        ),
    ]
