# Generated by Django 2.2.7 on 2020-06-09 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bancos', '0001_initial'),
        ('movimientos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocontable',
            name='aport_retiro',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movimientos.Movimiento'),
        ),
        migrations.AddField(
            model_name='registrocontable',
            name='movimiento_banco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bancos.MovimientoBanco'),
        ),
    ]
