# Generated by Django 2.2.7 on 2020-04-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientobanco',
            name='referencia_banco',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
