# Generated by Django 2.2.7 on 2020-12-17 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bancos', '0002_auto_20201217_1628'),
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocontable',
            name='pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pagos.Pago'),
        ),
        migrations.AddField(
            model_name='registrocontable',
            name='subcuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bancos.SubCuenta'),
        ),
    ]
