# Generated by Django 2.2.7 on 2022-02-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0004_movimientobanco_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='externo',
            field=models.BooleanField(default=False),
        ),
    ]
