# Generated by Django 2.2.7 on 2020-06-27 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_auto_20200627_1532'),
        ('bancos', '0005_auto_20200612_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocontable',
            name='ej_credito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contratos.ContratoCredito'),
        ),
    ]
