# Generated by Django 2.2.7 on 2020-07-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0006_registrocontable_ej_credito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrocontable',
            name='referencia',
        ),
        migrations.AddField(
            model_name='movimientobanco',
            name='nota',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
