# Generated by Django 2.2.7 on 2020-07-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0007_auto_20200703_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcuenta',
            name='nombre',
            field=models.CharField(max_length=60),
        ),
    ]
