# Generated by Django 2.2.7 on 2020-07-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0008_auto_20200703_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcuenta',
            name='sistema',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
