# Generated by Django 2.2.7 on 2020-07-24 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0009_subcuenta_sistema'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimientobanco',
            old_name='nota',
            new_name='referencia_alf',
        ),
    ]
