# Generated by Django 2.2.7 on 2020-08-17 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bancos', '0010_auto_20200724_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientobanco',
            name='fecha_auto',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientobanco',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='movimiento_banco', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
