# Generated by Django 2.2.7 on 2019-11-19 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tsumbalil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socios',
            fields=[
                ('clave_socio', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=50)),
                ('curp', models.CharField(blank=True, max_length=18, verbose_name='CURP')),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_ingr_yomol_atel', models.DateField()),
                ('fecha_ingr_programa', models.DateField()),
                ('prod_trab', models.CharField(choices=[('PR', 'Productor'), ('TR', 'Trabajador')], max_length=2)),
                ('clave_anterior', models.CharField(blank=True, max_length=10, null=True)),
                ('estatus_cafe', models.CharField(choices=[('AC', 'Activo'), ('NP', 'No Participa'), ('BA', 'Baja')], max_length=2)),
                ('estatus_miel', models.CharField(choices=[('AC', 'Activo'), ('NP', 'No Participa'), ('BA', 'Baja')], max_length=2)),
                ('estatus_yip', models.CharField(choices=[('AC', 'Activo'), ('NP', 'No Participa'), ('BA', 'Baja')], max_length=2)),
                ('estatus_gral', models.CharField(choices=[('AC', 'Activo'), ('NP', 'No Participa'), ('BA', 'Baja')], max_length=2)),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tsumbalil.Cargos')),
                ('comunidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tsumbalil.Comunidades')),
            ],
        ),
    ]
