# Generated by Django 2.2.7 on 2019-11-27 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsumbalil', '0001_initial'),
        ('users', '0001_initial'),
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Socios',
            new_name='Socio',
        ),
    ]
