# Generated by Django 2.2.7 on 2020-10-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='fecha_ingr_programa',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='fecha_ingr_yomol_atel',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
