# Generated by Django 2.2.7 on 2019-11-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socio',
            name='prod_trab',
        ),
        migrations.AddField(
            model_name='socio',
            name='productor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socio',
            name='trabajador',
            field=models.BooleanField(default=False),
        ),
    ]
