# Generated by Django 2.2.7 on 2020-01-21 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tsumbalil', '0002_cargocoop'),
        ('socios', '0002_auto_20191130_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='cargo_coop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tsumbalil.CargoCoop'),
        ),
    ]
