# Generated by Django 2.2.7 on 2020-11-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0003_socio_doc_rfc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
