# Generated by Django 2.2.7 on 2020-01-22 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tsumbalil', '0003_empresa'),
        ('socios', '0003_socio_cargo_coop'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tsumbalil.Empresa'),
        ),
    ]
