# Generated by Django 2.2.7 on 2020-03-17 13:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tsumbalil', '0003_empresa'),
        ('socios', '0004_socio_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socio',
            name='productor',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='trabajador',
        ),
        migrations.AddField(
            model_name='socio',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socio',
            name='estatus_trabajador',
            field=models.CharField(choices=[('AC', 'Activo'), ('NP', 'No Participa'), ('BA', 'Baja')], default='NP', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socio',
            name='genero',
            field=models.CharField(choices=[('MA', 'Masculino'), ('FE', 'Femenino'), ('OT', 'Otro')], default='MA', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socio',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='socio',
            name='cargo_coop',
        ),
        migrations.AddField(
            model_name='socio',
            name='cargo_coop',
            field=models.ManyToManyField(default=1, related_name='Socio', to='tsumbalil.CargoCoop'),
        ),
    ]
