# Generated by Django 2.2.7 on 2020-11-17 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0004_auto_20201112_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='comunidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tsumbalil.Comunidad'),
            preserve_default=False,
        ),
    ]
