# Generated by Django 2.2.7 on 2020-03-17 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tsumbalil', '0004_fuente_puesto_trabajo'),
        ('socios', '0005_auto_20200317_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='doc_act_nac',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socio',
            name='doc_curp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socio',
            name='doc_domicilio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socio',
            name='doc_ine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socio',
            name='puesto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Socio_puesto', to='tsumbalil.Puesto_Trabajo'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='cargo_coop',
            field=models.ManyToManyField(default=1, related_name='Socio_cargo_coop', to='tsumbalil.CargoCoop'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='empresa',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tsumbalil.Empresa'),
        ),
    ]
