# Generated by Django 2.2.7 on 2020-03-17 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tsumbalil', '0004_fuente_puesto_trabajo'),
        ('socios', '0006_auto_20200317_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='fuente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Socio_fuente', to='tsumbalil.Fuente'),
        ),
    ]
