# Generated by Django 2.2.7 on 2020-03-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0007_socio_fuente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socio',
            old_name='apellidos',
            new_name='apellido_materno',
        ),
        migrations.AddField(
            model_name='socio',
            name='apellido_paterno',
            field=models.CharField(default='--', max_length=50),
            preserve_default=False,
        ),
    ]
