# Generated by Django 2.2.7 on 2020-03-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0008_auto_20200317_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='cargo_coop',
            field=models.ManyToManyField(blank=True, default=1, related_name='Socio_cargo_coop', to='tsumbalil.CargoCoop'),
        ),
    ]
