# Generated by Django 2.2.7 on 2020-03-17 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0009_auto_20200317_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socio',
            old_name='estatus_gral',
            new_name='estatus_comonSit',
        ),
    ]
