# Generated by Django 2.2.7 on 2020-01-28 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tsumbalil', '0003_empresa'),
        ('socios', '0004_socio_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_entrega', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fecha_banco', models.DateField()),
                ('aportacion', models.BooleanField(default=True)),
                ('efectivo', models.BooleanField(default=False, null=True)),
                ('clave_socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimiento', to='socios.Socio')),
                ('empresa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tsumbalil.Empresa')),
            ],
        ),
    ]
