# Generated by Django 2.2.7 on 2020-06-09 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socios', '0001_initial'),
        ('bancos', '0003_auto_20200609_1709'),
        ('movimientos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimiento_autor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='clave_socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimiento', to='socios.Socio'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='referencia_banco_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimiento', to='bancos.MovimientoBanco'),
        ),
    ]
