# Generated by Django 2.2.7 on 2020-01-30 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='efectivo',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='tipo_de_movimiento',
            field=models.CharField(blank=True, choices=[('EF', 'Efectivo'), ('BA', 'Bancos'), ('TR', 'Transferencia')], max_length=2),
        ),
    ]
