# Generated by Django 2.2.7 on 2020-09-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='tipo_de_movimiento',
            field=models.CharField(choices=[('EF', 'Efectivo'), ('BA', 'Bancos'), ('TR', 'Transferencia')], max_length=2),
        ),
    ]
