# Generated by Django 2.2.7 on 2020-03-18 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movimientos', '0002_auto_20200130_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='empresa',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='autor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='movimiento_autor', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimiento',
            name='proceso',
            field=models.CharField(choices=[('CF', 'Cafe'), ('MI', 'Miel'), ('JA', 'Jabon'), ('SL', 'Sueldos')], default='CF', max_length=2),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='referencia_banco',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='responsable_entrega',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fecha_banco',
            field=models.DateField(blank=True),
        ),
    ]
