# Generated by Django 2.2.7 on 2020-04-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0002_auto_20200329_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
