# Generated by Django 2.2.7 on 2020-03-18 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0003_auto_20200318_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='fecha_banco',
            field=models.DateField(blank=True, null=True),
        ),
    ]
