# Generated by Django 2.2.7 on 2020-07-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0003_remove_movimiento_referencia_banco_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='ordinario',
            field=models.BooleanField(default=True),
        ),
    ]
