# Generated by Django 2.2.7 on 2020-03-19 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0004_auto_20200318_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='referencia_banco',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
