# Generated by Django 2.2.7 on 2020-03-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0005_auto_20200319_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='proceso',
            field=models.CharField(choices=[('CF', 'Café'), ('MI', 'Miel'), ('JA', 'Jabon'), ('SL', 'Sueldos')], default='CF', max_length=2),
        ),
    ]
