# Generated by Django 2.2.7 on 2020-12-17 16:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import tsumbalil.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ermitas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_cargo', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='CargoCoop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cargo_coop', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Fuente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuente', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Puesto_Trabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_region', models.CharField(max_length=40)),
                ('poly', django.contrib.gis.db.models.fields.PolygonField(default=None, null=True, srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Regiones',
            },
        ),
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_comunidad', models.CharField(max_length=50)),
                ('ermita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ermitas.Ermita')),
                ('inegi_extra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ermitas.InegiLocalidad')),
                ('region', models.ForeignKey(blank=True, default=tsumbalil.models.get_region_sin_asignar, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tsumbalil.Region')),
            ],
            options={
                'verbose_name_plural': 'Comunidades',
                'unique_together': {('nombre_de_comunidad', 'region')},
            },
        ),
    ]
