# Generated by Django 2.2.7 on 2020-01-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsumbalil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoCoop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cargo_coop', models.CharField(max_length=40)),
            ],
        ),
    ]
