# Generated by Django 2.2.7 on 2020-09-16 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ermitas', '0001_initial'),
        ('tsumbalil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='ermita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ermitas.Ermita'),
        ),
    ]
