# Generated by Django 2.2.7 on 2019-11-27 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_auto_20191127_2204'),
        ('tsumbalil', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cargos',
            new_name='Cargo',
        ),
        migrations.RenameModel(
            old_name='Comunidades',
            new_name='Comunidad',
        ),
        migrations.RenameModel(
            old_name='Regiones',
            new_name='Region',
        ),
        migrations.AlterModelOptions(
            name='comunidad',
            options={'verbose_name_plural': 'Comunidades'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name_plural': 'Regiones'},
        ),
    ]
