# Generated by Django 2.2.7 on 2020-04-11 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsumbalil', '0002_subcuenta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCuenta',
        ),
    ]
