# Generated by Django 2.2.7 on 2020-11-20 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsumbalil', '0004_auto_20201022_2057'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comunidad',
            unique_together={('nombre_de_comunidad', 'region')},
        ),
    ]
