# Generated by Django 2.2.7 on 2020-11-20 15:17

from django.db import migrations, models
import django.db.models.deletion
import tsumbalil.models


class Migration(migrations.Migration):

    dependencies = [
        ('tsumbalil', '0005_auto_20201120_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunidad',
            name='region',
            field=models.ForeignKey(blank=True, default=tsumbalil.models.get_region_sin_asignar, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tsumbalil.Region'),
        ),
    ]
