# Generated by Django 2.2.7 on 2020-12-10 23:27

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsumbalil', '0006_auto_20201120_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='poly',
            field=django.contrib.gis.db.models.fields.PolygonField(default=None, null=True, srid=4326),
        ),
    ]
