# Generated by Django 2.2.7 on 2020-05-16 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interzona',
            fields=[
                ('interzona_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('municipio_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('zona_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('interzona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ermitas.Interzona')),
            ],
        ),
        migrations.CreateModel(
            name='InegiLocalidades',
            fields=[
                ('localidad_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('altitud', models.IntegerField()),
                ('longitud', models.FloatField()),
                ('latitud', models.FloatField()),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ermitas.Municipio')),
            ],
        ),
        migrations.CreateModel(
            name='Ermita',
            fields=[
                ('ermita_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ermitas.Municipio')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ermitas.Zona')),
            ],
        ),
    ]
