# Generated by Django 2.2.7 on 2020-12-17 16:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interzona',
            fields=[
                ('interzona_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('municipio_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('zona_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('poly', django.contrib.gis.db.models.fields.MultiPolygonField(default=None, null=True, srid=4326)),
                ('poly_encuesta', django.contrib.gis.db.models.fields.MultiPolygonField(default=None, null=True, srid=4326)),
                ('interzona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ermitas.Interzona')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='InegiLocalidad',
            fields=[
                ('localidad_id', models.IntegerField(primary_key=True, serialize=False)),
                ('clave', models.IntegerField(default=0)),
                ('nombre', models.CharField(max_length=100)),
                ('altitud', models.IntegerField(default=0)),
                ('poblacion', models.IntegerField(default=0)),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ermitas.Municipio')),
            ],
            options={
                'verbose_name': 'INEGI localidad',
                'verbose_name_plural': 'INEGI localidades',
                'ordering': ['municipio', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ermita',
            fields=[
                ('ermita_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('localidad_nota', models.CharField(blank=True, max_length=100)),
                ('localidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ermitas.InegiLocalidad')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ermitas.Municipio')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ermitas.Zona')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
