# Generated by Django 2.2.7 on 2020-05-16 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ermitas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InegiLocalidades',
            new_name='InegiLocalidad',
        ),
    ]
