# Generated by Django 2.2.7 on 2020-12-16 17:38

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ermitas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zona',
            name='poly',
            field=django.contrib.gis.db.models.fields.PolygonField(default=None, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='zona',
            name='poly_encuesta',
            field=django.contrib.gis.db.models.fields.PolygonField(default=None, null=True, srid=4326),
        ),
    ]
