# Generated by Django 2.2.7 on 2020-12-16 19:14

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ermitas', '0002_auto_20201216_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zona',
            name='poly',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(default=None, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='zona',
            name='poly_encuesta',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(default=None, null=True, srid=4326),
        ),
    ]
