# Generated by Django 2.2.7 on 2020-05-18 20:45

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ermitas', '0002_auto_20200516_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='inegilocalidad',
            name='ubicacion',
            field=django.contrib.gis.db.models.fields.PointField(default=None, srid=4326),
            preserve_default=False,
        ),
    ]
