# Generated by Django 3.0.6 on 2020-05-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ermitas', '0003_inegilocalidad_ubicacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ermita',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='inegilocalidad',
            options={'ordering': ['municipio', 'nombre']},
        ),
        migrations.AlterModelOptions(
            name='interzona',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='municipio',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='zona',
            options={'ordering': ['nombre']},
        ),
        migrations.RemoveField(
            model_name='inegilocalidad',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='inegilocalidad',
            name='longitud',
        ),
        migrations.AddField(
            model_name='inegilocalidad',
            name='clave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inegilocalidad',
            name='poblacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inegilocalidad',
            name='altitud',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inegilocalidad',
            name='localidad_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
