# Generated by Django 3.0.6 on 2020-05-25 22:56

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ermitas', '0004_auto_20200525_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inegilocalidad',
            name='ubicacion',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
    ]
