# Generated by Django 2.2.7 on 2019-11-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acopios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('ingreso', models.DecimalField(decimal_places=2, max_digits=6)),
                ('kilosDeProducto', models.IntegerField(blank=True, null=True)),
                ('tipoDeProducto', models.CharField(blank=True, choices=[('CF', 'Cafe'), ('MI', 'Miel'), ('JA', 'Jabon'), ('SL', 'Sueldos')], max_length=2)),
            ],
        ),
    ]
