# Generated by Django 2.2.7 on 2019-11-27 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acopios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Acopios',
            new_name='Acopio',
        ),
    ]
