# Generated by Django 2.2.7 on 2020-04-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acopios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acopio',
            name='ingreso',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='acopio',
            name='kilos_de_producto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
