# Generated by Django 2.2.7 on 2020-03-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acopios', '0002_acopio_clave_socio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acopio',
            name='tipo_de_producto',
            field=models.CharField(blank=True, choices=[('CF', 'Café'), ('MI', 'Miel'), ('JA', 'Jabon'), ('SL', 'Sueldos')], max_length=2),
        ),
    ]
