# Generated by Django 2.2.7 on 2019-11-18 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acopios', '0002_auto_20191118_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acopios',
            name='fecha',
            field=models.DateField(),
        ),
    ]
