# Generated by Django 2.2.7 on 2020-03-29 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('creditos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcredito',
            name='promotor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solic_promotor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatsolicitudcredito',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='creditos.SolicitudCredito'),
        ),
        migrations.AddField(
            model_name='chatsolicitudcredito',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_solic', to=settings.AUTH_USER_MODEL),
        ),
    ]
