# Generated by Django 2.2.7 on 2020-04-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0002_auto_20200329_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcredito',
            name='justificacion_credito',
            field=models.CharField(max_length=100),
        ),
    ]
