# Generated by Django 2.2.7 on 2019-12-10 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0002_solicitudcredito_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcredito',
            name='irregularidades',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='pregunta_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='pregunta_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='pregunta_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='pregunta_4',
            field=models.BooleanField(default=False),
        ),
    ]
