# Generated by Django 2.2.7 on 2019-12-12 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_auto_20191130_1708'),
        ('creditos', '0003_auto_20191210_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcredito',
            name='aval',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='aval', to='socios.Socio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='familiar_responsable',
            field=models.CharField(default='Martina Hernandez', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='clave_socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitud', to='socios.Socio'),
        ),
    ]
