# Generated by Django 2.2.7 on 2020-01-21 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0004_auto_20191212_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcredito',
            name='comentarios_gerente',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
