# Generated by Django 2.2.7 on 2020-03-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0006_auto_20200221_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcredito',
            name='estatus_evaluacion',
            field=models.CharField(choices=[('AP', 'Aprobado'), ('RV', 'Revisión'), ('NE', 'Negociación'), ('CA', 'Cancelado')], max_length=2),
        ),
    ]
