# Generated by Django 2.2.7 on 2020-03-21 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0007_auto_20200320_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudcredito',
            name='estatus_ej_credito',
        ),
    ]
