# Generated by Django 2.2.7 on 2020-03-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0009_auto_20200323_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcredito',
            name='proceso',
            field=models.CharField(choices=[('CF', 'Cafe'), ('MI', 'Miel'), ('JA', 'Jabon'), ('SL', 'Sueldos')], default='CF', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='act_productiva',
            field=models.CharField(blank=True, choices=[('CA', 'Cafetal'), ('VI', 'Viveros'), ('HR', 'Hortalizas'), ('GE', 'Ganado Vacuno (engorda)'), ('GC', 'Ganado Vacuno (pie de cría)'), ('PE', 'Ganado Porcino (engorda)'), ('PC', 'Ganado Porcino (pie de cría)'), ('AT', 'Aves de Traspatio'), ('MI', 'Milpa'), ('EL', 'Elaboración de Alimentos'), ('ER', 'Elaboración de Artesanía'), ('HE', 'Herramientas y Equipo de Trabajo'), ('OT', 'Otro')], max_length=2),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='mot_credito',
            field=models.CharField(choices=[('SA', 'Salud'), ('AL', 'Alimento'), ('TR', 'Trabajo'), ('ED', 'Educación'), ('FI', 'Fiestas'), ('OT', 'Otro')], max_length=2),
        ),
    ]
