# Generated by Django 2.2.7 on 2020-03-29 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0011_auto_20200326_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcredito',
            name='pregunta_1',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='pregunta_2',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='pregunta_3',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='pregunta_4',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
