# Generated by Django 2.2.7 on 2020-04-07 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoCredito',
            fields=[
                ('folio', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=9)),
                ('plazo', models.PositiveSmallIntegerField()),
                ('tasa', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('prorroga', models.DateField(blank=True, null=True)),
                ('estatus', models.CharField(choices=[('EC', 'En curso'), ('RE', 'Retraso'), ('CA', 'Cancelado')], max_length=2)),
                ('estatus_efectivo', models.CharField(choices=[('CO', 'Cobrado'), ('PC', 'Por cobrar'), ('CA', 'Cancelado')], max_length=2)),
                ('fecha_salida_banco', models.DateTimeField(blank=True, null=True)),
                ('estatus_ejecucion', models.CharField(choices=[('CO', 'Cobrado'), ('PC', 'Por cobrar'), ('RV', 'Revisión')], max_length=2)),
                ('clave_socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to='socios.Socio')),
                ('promotor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to='solicitudes.SolicitudCredito')),
            ],
        ),
    ]
