# Generated by Django 2.2.7 on 2020-05-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratocredito',
            name='iva',
            field=models.BooleanField(default=True),
        ),
    ]
