# Generated by Django 2.2.7 on 2020-04-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratocredito',
            name='estatus_efectivo',
        ),
        migrations.RemoveField(
            model_name='contratocredito',
            name='promotor',
        ),
        migrations.AddField(
            model_name='contratocredito',
            name='referencia_banco',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contratocredito',
            name='estatus',
            field=models.CharField(choices=[('DP', 'Deuda Pendiente'), ('PA', 'Pagado')], max_length=2),
        ),
        migrations.AlterField(
            model_name='contratocredito',
            name='estatus_ejecucion',
            field=models.CharField(choices=[('CO', 'Cobrado'), ('PC', 'Por cobrar'), ('CA', 'Cancelado')], max_length=2),
        ),
        migrations.AlterField(
            model_name='contratocredito',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contratocredito',
            name='fecha_salida_banco',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contratocredito',
            name='tasa',
            field=models.DecimalField(decimal_places=4, default=2, max_digits=7),
            preserve_default=False,
        ),
    ]
