# Generated by Django 2.2.7 on 2020-06-27 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_contratocredito_solicitud'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contratocredito',
            old_name='fecha_salida_banco',
            new_name='fecha_banco',
        ),
    ]
