# Generated by Django 2.2.7 on 2020-11-24 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_contratocredito_solicitud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratocredito',
            name='iva',
        ),
    ]
