# Generated by Django 2.2.7 on 2021-03-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_contratocredito_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratocredito',
            name='prorroga',
            field=models.SmallIntegerField(default=0),
        ),
    ]
