# Generated by Django 2.2.7 on 2021-03-24 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_auto_20210302_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratocredito',
            name='estatus',
            field=models.CharField(choices=[('DP', 'Deuda Pendiente'), ('PA', 'Pagado'), ('CN', 'Condonado')], max_length=2),
        ),
    ]
