# Generated by Django 2.2.7 on 2020-04-13 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_auto_20200413_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratocredito',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
