# Generated by Django 2.2.7 on 2021-03-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_auto_20210324_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratocredito',
            name='prorroga_justificacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
