# Generated by Django 2.2.7 on 2022-02-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0005_contratocredito_prorroga_justificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratocredito',
            name='fondo_comun',
            field=models.BooleanField(default=False),
        ),
    ]
