# Generated by Django 2.2.7 on 2020-04-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0005_contratocredito_tasa_moratoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratocredito',
            name='tipo_tasa',
            field=models.CharField(choices=[('FI', 'Fija'), ('VA', 'Variable')], default='FI', max_length=2),
            preserve_default=False,
        ),
    ]
